// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import Footer from "@/components/Footer";
import ResponsiveSidebarHeader from "@/components/ResponsiveSidebarHeader";
import { getClasses } from "../../../lib/getClasses";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="h-screen flex flex-col">
      <ResponsiveSidebarHeader />
      {children}
      
      <Footer backgroundColor="bg-gray-900" />
    </div>
  );
}