version: "3.8"

services:
  nextjs:
    image: node:18
    container_name: nextjs_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@mysql:3306/projet
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: projet
      MYSQL_USER: root
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - C:/Users/menis/docker.sql:/docker-entrypoint-initdb.d/docker.sql:ro  # Monte le script SQL dans MySQL

volumes:
  mysql_data:
