// @ts-nocheck


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import React from "react";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <head>
        <title>Correction de Copies</title>
      </head>
      <body className="h-screen flex flex-col">
        <nav className="bg-blue-600 text-white p-4 text-center font-bold">
          Correction de Copies
        </nav>
        {children}
        <footer>
          <Footer 
          backgroundColor="bg-gray-900" // Fond sombre
          textColor="text-gray-300" // Texte clair
          iconColor="text-gray-300"/>
        </footer>
      </body>
    </html>
  );
}
